Repository fib-international/structuralcodes, pull requests merged in 2024-10, with the labels that each got.

#181 fix: swap order of strain limits returned from get_ultimate_strain
  structuralcodes/core/base.py
  structuralcodes/materials/constitutive_laws.py
  structuralcodes/sections/_generic.py
  tests/test_core/test_constitutive_laws.py
Labels: enhancement

#182 fix: interaction domain results
  docs/api/sections/section_calculator.md
  structuralcodes/core/_section_results.py
  structuralcodes/sections/_generic.py
Labels: enhancement

#183 fix: moved methods for adding reinforcement into geometry module
  docs/api/geometry/geometry_creation.md
  docs/api/sections/section_creation.md
  docs/quickstart/quickstart_example.py
  structuralcodes/geometry/__init__.py
  structuralcodes/geometry/_reinforcement.py
  structuralcodes/sections/__init__.py
  tests/test_core/test_generic_section.py
  tests/test_core/test_geometry.py
Labels: enhancement

#184 fix: specify unit theta
  structuralcodes/sections/_generic.py
Labels: documentation, enhancement

#186 feat: more robust set design code
  structuralcodes/codes/__init__.py
  tests/test_core/test_get_set_design_code.py
Labels: enhancement

#192 bug: fix ec2 2004 exponent in calculation of beta_ds
  structuralcodes/codes/ec2_2004/annex_b_shrink_and_creep.py
  tests/test_ec2_2004/test_ec2_2004_annex_B_shrink_and_creep.py
Labels: bug

#193 fix: mc2010 beta_ds correct for time less than ts
  structuralcodes/codes/mc2010/_concrete_creep_and_shrinkage.py
Labels: bug, enhancement

#189 feat: add kwarg group_label to add_reinforcement functions
  structuralcodes/geometry/_reinforcement.py
  tests/test_core/test_geometry.py
Labels: enhancement

#195 docs: add properties of material classes to API docs
  docs/api/materials/concretes.md
  docs/api/materials/reinforcement_steels.md
Labels: documentation

#196 feat: ec2-2004 expose crdc in shear resistance
  structuralcodes/codes/ec2_2004/shear.py
Labels: enhancement

#191 fix: use also relative tolerance when checking calculated Iyz
  structuralcodes/sections/_generic.py
Labels: enhancement

#199 docs: improve description of kwargs passed from section to calculator
  docs/api/sections/section_calculator.md
  structuralcodes/sections/_generic.py
Labels: documentation

#194 fix: tidy api of ec2 2004 creep and shrinkage
  docs/api/codes/ec2_2004/creep_shrinkage.md
  structuralcodes/codes/ec2_2004/__init__.py
  structuralcodes/codes/ec2_2004/_concrete_creep_and_shrinkage.py
  structuralcodes/codes/ec2_2004/annex_b_shrink_and_creep.py
  tests/test_ec2_2004/test_ec2_2004_annex_B_shrink_and_creep.py
  tests/test_ec2_2004/test_ec2_2004_shrinkage_and_creep.py
Labels: enhancement

#202 fix: Constitutive law fixes and refactoring
  structuralcodes/core/base.py
  structuralcodes/geometry/_geometry.py
  structuralcodes/materials/constitutive_laws.py
  structuralcodes/materials/constitutive_laws/__init__.py
  structuralcodes/materials/constitutive_laws/_bilinearcompression.py
  structuralcodes/materials/constitutive_laws/_elastic.py
  structuralcodes/materials/constitutive_laws/_elasticplastic.py
  structuralcodes/materials/constitutive_laws/_parabolarectangle.py
  structuralcodes/materials/constitutive_laws/_popovics.py
  structuralcodes/materials/constitutive_laws/_sargin.py
  structuralcodes/materials/constitutive_laws/_userdefined.py
  structuralcodes/sections/_generic.py
  structuralcodes/sections/section_integrators/_marin_integrator.py
  tests/test_materials/test_constitutive_laws.py
Labels: enhancement, constitutive laws
