Repository fib-international/structuralcodes, pull requests merged in 2025-08, with the labels that each got.

#262 feat: Implement InitStrain
  docs/api/materials/constitutive_laws.md
  structuralcodes/core/base.py
  structuralcodes/materials/basic/_elastic.py
  structuralcodes/materials/basic/_elasticplastic.py
  structuralcodes/materials/basic/_generic.py
  structuralcodes/materials/concrete/_concrete.py
  structuralcodes/materials/concrete/_concreteEC2_2004.py
  structuralcodes/materials/concrete/_concreteEC2_2023.py
  structuralcodes/materials/concrete/_concreteMC2010.py
  structuralcodes/materials/constitutive_laws/__init__.py
  structuralcodes/materials/constitutive_laws/_elasticplastic.py
  structuralcodes/materials/constitutive_laws/_initial_strain.py
  structuralcodes/materials/reinforcement/_reinforcement.py
  structuralcodes/materials/reinforcement/_reinforcementEC2_2004.py
  structuralcodes/materials/reinforcement/_reinforcementEC2_2023.py
  structuralcodes/materials/reinforcement/_reinforcementMC2010.py
  tests/test_materials/test_constitutive_laws.py
  tests/test_materials/test_marin_coefficiens.py
  tests/test_materials/test_reinforcements.py
  tests/test_sections/test_generic_section.py
Labels: enhancement

#266 docs: add usage guide
  docs/_example_code/quickstart_example.py
  docs/_example_code/usage_compute_stress_strain.py
  docs/_example_code/usage_create_constitutive_law_factory.py
  docs/_example_code/usage_create_elastic_material_from_other.py
  docs/_example_code/usage_create_elasticplastic_material.py
  docs/_example_code/usage_create_materials_factory.py
  docs/_example_code/usage_create_specific_concrete.py
  docs/_example_code/usage_create_specific_reinforcement.py
  docs/_example_code/usage_create_surface_geometries.py
  docs/_example_code/usage_create_surface_geometries_simple.py
  docs/_example_code/usage_create_surface_geometries_with_reinforcement.py
  docs/_example_code/usage_steel_profile_in_geometry.py
  docs/_example_code/usage_steel_profiles.py
  docs/api/geometry/geometry_creation.md
  docs/api/materials/base_materials.md
  docs/api/materials/basic_materials.md
  docs/api/materials/concretes.md
  docs/api/materials/constitutive_laws.md
  docs/api/materials/index.md
  docs/api/materials/reinforcement_steels.md
  docs/conf.py
  docs/examples/index.md
  docs/index.md
  docs/quickstart/index.md
  docs/usage/geometries/hea100.svg
  docs/usage/geometries/index.md
  docs/usage/geometries/t_shaped_geometry.svg
  docs/usage/geometries/t_shaped_geometry_with_reinforcement.svg
  docs/usage/index.md
  docs/usage/materials/index.md
  docs/usage/materials/parabola_rectangle.png
  docs/usage/sections/index.md
  docs/usage/sections/moment_curvature.png
Labels: documentation

#256 feat: add tests shell section
  tests/test_sections/test_shell_section.py
Labels: enhancement

#272 chore: upgrade pipeline
  .github/workflows/build.yaml
  docs/installation/index.md
  makefile
  pyproject.toml
  structuralcodes/codes/mc2010/_concrete_creep_and_shrinkage.py
  structuralcodes/core/base.py
  structuralcodes/geometry/_reinforcement.py
  tests/test_core/test_rc_utils.py
  tests/test_geometry/test_geometry.py
  tox.ini
Labels: chore

#275 feat: split transform method
  structuralcodes/materials/constitutive_laws/_parabolarectangle_2d.py
Labels: enhancement
