Repository fib-international/structuralcodes, pull requests merged in 2025-01, with the labels that each got.

#200 feat: Rectangular Section
  docs/api/geometry/geometry_creation.md
  structuralcodes/geometry/__init__.py
  structuralcodes/geometry/_rectangular.py
  tests/test_geometry/test_rectangular.py
Labels: enhancement, sections

#161 feat: Strain profile n my mz
  .gitignore
  docs/api/sections/section_calculator.md
  structuralcodes/sections/_generic.py
  tests/test_sections/test_generic_section.py
Labels: enhancement, sections

#212 docs: update docs
  docs/api/sections/section_integrator.md
  docs/conf.py
  docs/requirements.txt
Labels: documentation

#213 feat: add origin kwarg to wrapper geom classes
  structuralcodes/geometry/_circular.py
  structuralcodes/geometry/_rectangular.py
  tests/test_geometry/test_circular.py
  tests/test_geometry/test_rectangular.py
Labels: enhancement

#217 fix: add missing kwargs in geometries
  structuralcodes/geometry/_circular.py
  structuralcodes/geometry/_geometry.py
  structuralcodes/geometry/_rectangular.py
  tests/test_geometry/test_circular.py
  tests/test_geometry/test_geometry.py
  tests/test_geometry/test_rectangular.py
Labels: bug, enhancement

#216 fix: get_stress in BilinearCompression
  structuralcodes/materials/constitutive_laws/_bilinearcompression.py
  tests/test_materials/test_constitutive_laws.py
Labels: bug
