Repository fib-international/structuralcodes, pull requests merged in 2025-03, with the labels that each got.

#209 feat: MC2010 bondslip
  docs/api/codes/mc2010/bond_reinforcement.md
  docs/api/codes/mc2010/index.md
  structuralcodes/codes/mc2010/__init__.py
  structuralcodes/codes/mc2010/_interface_concrete_steel_rebar.py
  tests/test_mc2010/test_mc2010_interface_concrete_steel_rebar.py
Labels: enhancement

#224 fix: bugfix moment curvature
  structuralcodes/sections/_generic.py
  tests/test_sections/test_generic_section.py
Labels: bug

#228 feat: implement shell geometry
  structuralcodes/geometry/_shell_geometry.py
Labels: enhancement, sections

#226 feat: make materials immutable
  structuralcodes/core/base.py
  structuralcodes/materials/concrete/_concrete.py
  structuralcodes/materials/concrete/_concreteEC2_2004.py
  structuralcodes/materials/concrete/_concreteEC2_2023.py
  structuralcodes/materials/concrete/_concreteMC2010.py
  structuralcodes/materials/constitutive_laws/__init__.py
  structuralcodes/materials/reinforcement/_reinforcement.py
  structuralcodes/materials/reinforcement/_reinforcementEC2_2004.py
  structuralcodes/materials/reinforcement/_reinforcementEC2_2023.py
  structuralcodes/materials/reinforcement/_reinforcementMC2010.py
  tests/test_ec2_2004/test_concrete_ec2_2004.py
  tests/test_ec2_2023/test_concrete_ec2_2023.py
  tests/test_materials/test_concrete.py
  tests/test_materials/test_reinforcements.py
  tests/test_mc2010/test_concrete_mc2010.py
  tests/test_sections/test_generic_section.py
Labels: enhancement

#230 docs: update docs
  docs/api/materials/base_materials.md
  structuralcodes/materials/concrete/_concreteEC2_2004.py
  structuralcodes/materials/concrete/_concreteEC2_2023.py
  structuralcodes/materials/concrete/_concreteMC2010.py
  structuralcodes/materials/reinforcement/_reinforcementEC2_2004.py
  structuralcodes/materials/reinforcement/_reinforcementEC2_2023.py
  structuralcodes/materials/reinforcement/_reinforcementMC2010.py
Labels: documentation

#223 fix: MC2010 punching refactoring and tests coverage improvements
  structuralcodes/codes/mc2010/_concrete_punching.py
  structuralcodes/sections/section_integrators/_fiber_integrator.py
  tests/test_mc2010/test_mc2010_concrete_punching.py
Labels: chore

#231 docs: Update api docs for punching according to mc2010
  docs/api/codes/mc2010/shear.md
  structuralcodes/codes/mc2010/__init__.py
  structuralcodes/codes/mc2010/_concrete_punching.py
  tests/test_mc2010/test_mc2010_concrete_punching.py
Labels: documentation

#232 fix: hardening modulus reinforcement
  structuralcodes/materials/reinforcement/_reinforcementEC2_2004.py
  structuralcodes/materials/reinforcement/_reinforcementEC2_2023.py
  structuralcodes/materials/reinforcement/_reinforcementMC2010.py
  tests/test_sections/test_generic_section.py
Labels: bug

#233 fix: annotate constitutive law property of base material
  structuralcodes/core/base.py
Labels: enhancement
