Repository fib-international/structuralcodes, pull requests merged in 2025-10, with the labels that each got.

#287 feat: concrete smeared cracking
  structuralcodes/materials/constitutive_laws/__init__.py
  structuralcodes/materials/constitutive_laws/_concrete_smeared_cracking/__init__.py
  structuralcodes/materials/constitutive_laws/_concrete_smeared_cracking/_core.py
  structuralcodes/materials/constitutive_laws/_concrete_smeared_cracking/_cracking_criterion.py
  structuralcodes/materials/constitutive_laws/_concrete_smeared_cracking/_poisson_reduction.py
  structuralcodes/materials/constitutive_laws/_concrete_smeared_cracking/_strength_reduction_lateral_cracking.py
  structuralcodes/materials/constitutive_laws/_concrete_smeared_cracking/_utils.py
  structuralcodes/materials/constitutive_laws/_parabolarectangle_2d.py
  tests/test_materials/test_constitutive_laws.py
  tests/test_sections/test_shell_section.py
Labels: sections, constitutive laws

#282 feat: add profiles
  structuralcodes/geometry/profiles/__init__.py
  structuralcodes/geometry/profiles/_common_functions.py
  structuralcodes/geometry/profiles/_hd.py
  structuralcodes/geometry/profiles/_hp.py
  structuralcodes/geometry/profiles/_l.py
  structuralcodes/geometry/profiles/_li.py
  structuralcodes/geometry/profiles/_u.py
  structuralcodes/geometry/profiles/_ub.py
  structuralcodes/geometry/profiles/_upe.py
  structuralcodes/geometry/profiles/_w.py
  tests/test_geometry/test_profiles/__init__.py
  tests/test_geometry/test_profiles/hd.json
  tests/test_geometry/test_profiles/hp.json
  tests/test_geometry/test_profiles/l.json
  tests/test_geometry/test_profiles/li.json
  tests/test_geometry/test_profiles/test_hd.py
  tests/test_geometry/test_profiles/test_hp.py
  tests/test_geometry/test_profiles/test_l.py
  tests/test_geometry/test_profiles/test_li.py
  tests/test_geometry/test_profiles/test_profiles.py
  tests/test_geometry/test_profiles/test_u.py
  tests/test_geometry/test_profiles/test_ub.py
  tests/test_geometry/test_profiles/test_upe.py
  tests/test_geometry/test_profiles/test_w.py
  tests/test_geometry/test_profiles/u.json
  tests/test_geometry/test_profiles/ub.json
  tests/test_geometry/test_profiles/upe.json
  tests/test_geometry/test_profiles/w.json
Labels: enhancement

#290 docs: update docs with recent API additions
  docs/api/geometry/geometry_creation.md
  docs/api/geometry/profiles.md
  structuralcodes/geometry/profiles/_hd.py
Labels: documentation
